### ISSUE TITLE
Change error message from Unauthorized to File missing

### ISSUE THREAD

**Issue by SanjeevKGupta** [open-horizon/edge-sync-service#51]
When I was following https://www.ibm.com/support/knowledgecenter/SSFKVV_4.2/installing/automated_install.html to do the CSS based install of the agent and got following error. This **Unauthorized** message made me go on a different tangent to debug.
2020-11-17 13:47:52 ERROR: could not download https://cp-console.ieam42-edge-8e873dd4c685acf6fd2f13f4cdfb05bb-0000.us-south.containers.appdomain.cloud/edge-css/api/v1/objects/IBM/agent_files/agent-install.crt/data: Unauthorized
It turned out that I had not pushed the files into CSS (as I had settled for alternate tar.gz based agent-install because of a different issue). May be a good idea to improve the message from **Unauthorized** to **agent-install.crt does not exist**

**Comment by LiilyZhang** [comment]
@edgedock @bmpotter When the object metadata is not exist, we do not treat it as "public" object. For the users that doesn't belongs to the org (in your case it is "IBM" org), we give 403. For the authorized users (belongs to the org or has been authorized to the org) we will give 404. 

Do you want to change the behavior so that unauthorized user can know if the object is exist or not in an unauthorized org?
